# Generated by Django 4.2.1 on 2023-06-01 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('species', models.CharField(max_length=15)),
                ('breed', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('image', models.ImageField(upload_to='media')),
                ('description', models.TextField(max_length=1500)),
            ],
            options={
                'db_table': 'PetsTable',
            },
        ),
    ]
