# Generated by Django 4.2.1 on 2023-06-14 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petsapp', '0003_author_books'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='Author_name',
            new_name='name',
        ),
    ]
