# Generated by Django 4.2.1 on 2023-06-20 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsapp', '0004_rename_author_name_author_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=20)),
                ('sname', models.ManyToManyField(to='petsapp.student')),
            ],
        ),
    ]
